# Static makefile
.include "${.CURDIR}/Makefile.sources"

CLANG_INCLUDES=	yes
INCSDIR=	${LIBDATADIR}/clangb
FILESDIR=	${LIBDATADIR}/clangb
FILES=		${GENINCS}

# Do not install headers doring make depend here.
depend:

.include <bsd.prog.mk>
